package com.mycompany.mavenproject2;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JFormattedTextField;
import javax.swing.text.MaskFormatter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author BadCatss
 */
public class RegistrationWindow extends javax.swing.JFrame {

    /**
     * Creates new form RegistrationWindow
     */
    public static HashMap<String, HashMap<Integer, Integer> > ParkedCars = new HashMap<>();
    public RegistrationWindow() {
        initComponents();
        
        char c ='A';
        for (int i = 0; i <  mainForm.ListOfParking.get(mainForm.SelectingParkingIndex).ParkObj_sectorCount; ++i) {
            ParkingSector_ComboBox.addItem(Character.toString(c));
            c++;
        }


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        Car_Label = new javax.swing.JLabel();
        Model_Label = new javax.swing.JLabel();
        ParkingSpasces_Label = new javax.swing.JLabel();
        ParkingSpace_Spinner = new javax.swing.JSpinner();
        ParkingPeriod_Label = new javax.swing.JLabel();
        Start_Label = new javax.swing.JLabel();
        Stop_Label = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        CarOwner_Label = new javax.swing.JLabel();
        OwnerName_TextField = new javax.swing.JTextField();
        StartD_FormattedTextField = new javax.swing.JFormattedTextField();
        StopD_FormattedTextField = new javax.swing.JFormattedTextField();
        RegProcStatus_Panel = new javax.swing.JPanel();
        ModelCorr_CheckBox = new javax.swing.JCheckBox();
        StartDateCorr_CheckBox = new javax.swing.JCheckBox();
        StopDateCorr_CheckBox = new javax.swing.JCheckBox();
        OwnerCorr_CheckBox = new javax.swing.JCheckBox();
        RegStatus_Label = new javax.swing.JLabel();
        Name_Label = new javax.swing.JLabel();
        Suname_Label = new javax.swing.JLabel();
        OwnerSuname_TextField = new javax.swing.JTextField();
        CarModel_ComboBox = new javax.swing.JComboBox<>();
        RegistrNewCar_Button = new javax.swing.JButton();
        Info_Panel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Info_TextArea = new javax.swing.JTextArea();
        Finish_Button = new javax.swing.JButton();
        ParkingSector_Label = new javax.swing.JLabel();
        ParkingSector_ComboBox = new javax.swing.JComboBox<>();

        jCheckBox1.setText("jCheckBox1");

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Car_Label.setText("Car:");

        Model_Label.setText("Model:");

        ParkingSpasces_Label.setText("It occupies parking spaces:");

        ParkingSpace_Spinner.setModel(new javax.swing.SpinnerNumberModel(1, 1, 4, 1));
        ParkingSpace_Spinner.setValue(1);

        ParkingPeriod_Label.setText("Parking period:");

        Start_Label.setText("Start:");

        Stop_Label.setText("Stop:");

        CarOwner_Label.setText("Car Owner:");

        OwnerName_TextField.setText("ivan");
        OwnerName_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                OwnerName_TextFieldFocusLost(evt);
            }
        });
        OwnerName_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                OwnerName_TextFieldKeyPressed(evt);
            }
        });

        StartD_FormattedTextField.setText("11-11-2011");
        StartD_FormattedTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                StartD_FormattedTextFieldKeyReleased(evt);
            }
        });

        StopD_FormattedTextField.setText("12-11-2011");
        StopD_FormattedTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                StopD_FormattedTextFieldKeyReleased(evt);
            }
        });

        RegProcStatus_Panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        RegProcStatus_Panel.setEnabled(false);
        RegProcStatus_Panel.setFocusable(false);

        ModelCorr_CheckBox.setSelected(true);
        ModelCorr_CheckBox.setText("Car model is correct");
        ModelCorr_CheckBox.setEnabled(false);

        StartDateCorr_CheckBox.setText("Parking start date is correct");
        StartDateCorr_CheckBox.setEnabled(false);

        StopDateCorr_CheckBox.setText("Parking stop date is correct");
        StopDateCorr_CheckBox.setEnabled(false);

        OwnerCorr_CheckBox.setText("Car owner is correct");
        OwnerCorr_CheckBox.setEnabled(false);

        javax.swing.GroupLayout RegProcStatus_PanelLayout = new javax.swing.GroupLayout(RegProcStatus_Panel);
        RegProcStatus_Panel.setLayout(RegProcStatus_PanelLayout);
        RegProcStatus_PanelLayout.setHorizontalGroup(
            RegProcStatus_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegProcStatus_PanelLayout.createSequentialGroup()
                .addGroup(RegProcStatus_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ModelCorr_CheckBox)
                    .addComponent(StartDateCorr_CheckBox)
                    .addComponent(StopDateCorr_CheckBox))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(RegProcStatus_PanelLayout.createSequentialGroup()
                .addComponent(OwnerCorr_CheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        RegProcStatus_PanelLayout.setVerticalGroup(
            RegProcStatus_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegProcStatus_PanelLayout.createSequentialGroup()
                .addComponent(ModelCorr_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StartDateCorr_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(StopDateCorr_CheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(OwnerCorr_CheckBox)
                .addGap(0, 45, Short.MAX_VALUE))
        );

        RegStatus_Label.setText("Parking registartion status:");

        Name_Label.setText("Name:");

        Suname_Label.setText("Suname:");

        OwnerSuname_TextField.setText("ivanov");
        OwnerSuname_TextField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                OwnerSuname_TextFieldFocusLost(evt);
            }
        });
        OwnerSuname_TextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                OwnerSuname_TextFieldKeyReleased(evt);
            }
        });

        CarModel_ComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Shkoda", "BMW", "Audi", "Aston Martin", "Buick" }));
        CarModel_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CarModel_ComboBoxActionPerformed(evt);
            }
        });

        RegistrNewCar_Button.setText("Register new car");
        RegistrNewCar_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistrNewCar_ButtonActionPerformed(evt);
            }
        });

        Info_Panel.setBorder(javax.swing.BorderFactory.createTitledBorder("Info label"));

        Info_TextArea.setColumns(20);
        Info_TextArea.setRows(5);
        Info_TextArea.setText("Input date at format: \"MM-dd-yyyy\"");
        jScrollPane1.setViewportView(Info_TextArea);

        javax.swing.GroupLayout Info_PanelLayout = new javax.swing.GroupLayout(Info_Panel);
        Info_Panel.setLayout(Info_PanelLayout);
        Info_PanelLayout.setHorizontalGroup(
            Info_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        Info_PanelLayout.setVerticalGroup(
            Info_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );

        Finish_Button.setText("Finish>>");
        Finish_Button.setEnabled(false);
        Finish_Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Finish_ButtonActionPerformed(evt);
            }
        });

        ParkingSector_Label.setText("Parking sector:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2)
            .addGroup(layout.createSequentialGroup()
                .addComponent(RegProcStatus_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Info_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(RegistrNewCar_Button)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Finish_Button)
                        .addGap(28, 28, 28))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RegStatus_Label)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Car_Label)
                                .addGap(18, 18, 18)
                                .addComponent(Model_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CarModel_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ParkingSpasces_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ParkingSpace_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ParkingSector_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(ParkingSector_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(ParkingPeriod_Label)
                                .addGap(58, 58, 58)
                                .addComponent(Start_Label)
                                .addGap(18, 18, 18)
                                .addComponent(StartD_FormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(Stop_Label)
                                .addGap(30, 30, 30)
                                .addComponent(StopD_FormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(CarOwner_Label)
                                .addGap(31, 31, 31)
                                .addComponent(Name_Label)
                                .addGap(21, 21, 21)
                                .addComponent(OwnerName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(12, 12, 12)
                                .addComponent(Suname_Label)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(OwnerSuname_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(68, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Car_Label)
                    .addComponent(Model_Label)
                    .addComponent(CarModel_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ParkingSpasces_Label)
                    .addComponent(ParkingSpace_Spinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ParkingSector_Label)
                    .addComponent(ParkingSector_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Start_Label)
                    .addComponent(ParkingPeriod_Label)
                    .addComponent(Stop_Label)
                    .addComponent(StartD_FormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StopD_FormattedTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CarOwner_Label)
                    .addComponent(OwnerName_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Name_Label)
                    .addComponent(Suname_Label)
                    .addComponent(OwnerSuname_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(RegStatus_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(Info_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RegistrNewCar_Button)
                            .addComponent(Finish_Button)))
                    .addComponent(RegProcStatus_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CarModel_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CarModel_ComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CarModel_ComboBoxActionPerformed

    private void RegistrNewCar_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistrNewCar_ButtonActionPerformed
        if (ModelCorr_CheckBox.isSelected() && StartDateCorr_CheckBox.isSelected()
                && StopDateCorr_CheckBox.isSelected() && OwnerCorr_CheckBox.isSelected()) {
            var parking1 = mainForm.ListOfParking.get(mainForm.SelectingParkingIndex);
           
            var place1 = parking1.TerminalSession().RegisterNewCar(mainForm.SelectParkingName ,
                    ParkingSector_ComboBox.getSelectedItem().toString().charAt(0),
                    Integer.parseInt( mainForm.PushedButtonText),
                    new Car(CarModel_ComboBox.getSelectedItem().toString(), 
                            (Integer)ParkingSpace_Spinner.getValue()), 
                    new ParkingTime(StartD_FormattedTextField.getText(), 
                            StopD_FormattedTextField.getText()), 
                    OwnerName_TextField.getText()+" "+OwnerSuname_TextField.getText()
            );
             ParkedCars.put(mainForm.PushedButtonText,place1 );

              if ((Integer)place1.values().toArray()[place1.values().size()-1]!=-1) {

                var d = parking1.TerminalSession().GetCarData((Integer) place1.values().toArray()[place1.values().size()-1]);
                Info_TextArea.append("\nparking cost for the selected period " + d.cost);
                Finish_Button.setEnabled(true);
            }

        }
    }//GEN-LAST:event_RegistrNewCar_ButtonActionPerformed

    private void StartD_FormattedTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StartD_FormattedTextFieldKeyReleased
        if (StartD_FormattedTextField.getText().matches("^(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])-[0-9]{4}$")) {
            StartDateCorr_CheckBox.setSelected(true);
        } else {
            StartDateCorr_CheckBox.setSelected(false);
        }
    }//GEN-LAST:event_StartD_FormattedTextFieldKeyReleased

    private void StopD_FormattedTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_StopD_FormattedTextFieldKeyReleased

        Date date1;
        Date date2;
        try {
            date1 = new SimpleDateFormat("MM-dd-yyyy").parse(StartD_FormattedTextField.getText());
            date2 = new SimpleDateFormat("MM-dd-yyyy").parse(StopD_FormattedTextField.getText());

            if (date1.before(date2)) {
                if (StopD_FormattedTextField.getText().matches("^(1[0-2]|0[1-9])-(3[01]|[12][0-9]|0[1-9])-[0-9]{4}$")) {
                    StopDateCorr_CheckBox.setSelected(true);
                } else {
                    StopDateCorr_CheckBox.setSelected(false);
                }

            }

        } catch (Exception e) {
        }


    }//GEN-LAST:event_StopD_FormattedTextFieldKeyReleased
    Boolean OwnerNameCorr = false;
    Boolean OwnerSunameCorr = false;
    private void OwnerName_TextFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OwnerName_TextFieldKeyPressed
        if (OwnerName_TextField.getText().matches("[a-zA-Z]{2,15}")) {
            OwnerNameCorr = true;
        } else {
            OwnerNameCorr = false;
        }
    }//GEN-LAST:event_OwnerName_TextFieldKeyPressed

    private void OwnerSuname_TextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OwnerSuname_TextFieldKeyReleased
        if (OwnerSuname_TextField.getText().matches("[a-zA-Z]{2,15}")) {
            OwnerSunameCorr = true;
        } else {
            OwnerSunameCorr = false;
        }
    }//GEN-LAST:event_OwnerSuname_TextFieldKeyReleased

    private void OwnerName_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OwnerName_TextFieldFocusLost
        if (OwnerNameCorr && OwnerSunameCorr) {
            OwnerCorr_CheckBox.setSelected(true);
        }
    }//GEN-LAST:event_OwnerName_TextFieldFocusLost

    private void OwnerSuname_TextFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_OwnerSuname_TextFieldFocusLost
        if (OwnerNameCorr && OwnerSunameCorr) {
            OwnerCorr_CheckBox.setSelected(true);
        }
    }//GEN-LAST:event_OwnerSuname_TextFieldFocusLost

    private void Finish_ButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Finish_ButtonActionPerformed
       mainForm.Registration_window.dispose();
       mainForm.PushedButton.setForeground(Color.red);
    }//GEN-LAST:event_Finish_ButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistrationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistrationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistrationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistrationWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistrationWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CarModel_ComboBox;
    private javax.swing.JLabel CarOwner_Label;
    private javax.swing.JLabel Car_Label;
    private javax.swing.JButton Finish_Button;
    private javax.swing.JPanel Info_Panel;
    private javax.swing.JTextArea Info_TextArea;
    private javax.swing.JCheckBox ModelCorr_CheckBox;
    private javax.swing.JLabel Model_Label;
    private javax.swing.JLabel Name_Label;
    private javax.swing.JCheckBox OwnerCorr_CheckBox;
    private javax.swing.JTextField OwnerName_TextField;
    private javax.swing.JTextField OwnerSuname_TextField;
    private javax.swing.JLabel ParkingPeriod_Label;
    private javax.swing.JComboBox<String> ParkingSector_ComboBox;
    private javax.swing.JLabel ParkingSector_Label;
    private javax.swing.JSpinner ParkingSpace_Spinner;
    private javax.swing.JLabel ParkingSpasces_Label;
    private javax.swing.JPanel RegProcStatus_Panel;
    private javax.swing.JLabel RegStatus_Label;
    private javax.swing.JButton RegistrNewCar_Button;
    private javax.swing.JFormattedTextField StartD_FormattedTextField;
    private javax.swing.JCheckBox StartDateCorr_CheckBox;
    private javax.swing.JLabel Start_Label;
    private javax.swing.JFormattedTextField StopD_FormattedTextField;
    private javax.swing.JCheckBox StopDateCorr_CheckBox;
    private javax.swing.JLabel Stop_Label;
    private javax.swing.JLabel Suname_Label;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    // End of variables declaration//GEN-END:variables
}
